-- Criação da tabela para armazenar as Ações Comerciais
create table public.comercial_actions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Campos vindos do Excel
  data text,
  nome text,
  fone text,
  acao text,
  origem_campanha text,
  canal_venda text,
  status_atendimento text,
  fechamento text,
  valor numeric,
  tipo_procedimento text,
  profissional text,
  observacoes text
);

-- Habilitar RLS (Row Level Security) é uma boa prática, 
-- mas para acesso via chave 'anon' pública sem login, precisamos criar uma política
alter table public.comercial_actions enable row level security;

-- Política para permitir leitura pública (se necessário)
create policy "Permitir leitura para todos"
on public.comercial_actions
for select
to anon
using (true);

-- Política para permitir inserção/atualização pública (cuidado com produção, mas ok para este teste)
create policy "Permitir salvar para todos"
on public.comercial_actions
for insert
to anon
with check (true);

create policy "Permitir atualizar para todos"
on public.comercial_actions
for update
to anon
using (true);
